#!/usr/bin/env zsh

PYTHON_VERSION="3.10.5"
ANSIBLE_VERSION="5.10.0"

if [ "$INITIALIZE" != "true" ] ; then
    echo "set INITIAILIZE=true, run"
    exit 1
fi

# install homebrew
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

# rosetta
sudo softwareupdate --install-rosetta

# install asdf
brew install asdf
echo -e ". $(brew --prefix asdf)/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc

# install python
asdf plugin add python
asdf install python $PYTHON_VERSION
asdf global python $PYTHON_VERSION

# check version
source ${ZDOTDIR:-~}/.zshrc
v=$(echo $(python -V) | sed 's/Python //')
if [ "$v" != "$PYTHON_VERSION" ] ; then
    echo "expect python version is $PYTHON_VERSION, but $v"
    exit 1
fi

# install pip
python -m ensurepip --upgrade

# install ansible
python -m pip install --user ansible==$ANSIBLE_VERSION
echo 'export PATH=$HOME/.local/bin:$PATH' >> ${ZDOTDIR:-~}/.zshrc

#
echo "please exec 'source ${ZDOTDIR:-~}/.zshrc'"
