## docker
alias d='docker'
alias dc='docker-compose'
alias dce='docker-compose exec'
alias dcs='docker-compose stop'
alias dcd='docker-compose down'
alias dcu='docker-compose up -d'
alias dcb='docker-compose build'
alias dcp='docker-compose ps'

## git
alias g='git'
alias gl="git log --graph --date=short --decorate=short --pretty=format:'%Cgreen%h %Creset%cd %Cblue%cn %Cred%d %Creset%s'"
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit --amend'
alias gps='git push'
alias gpl='git pull'
alias gs='git status'
alias gco='git checkout'
alias gb='git branch'
alias gcp='git cherry-pick'
alias gm='git merge --no-ff'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias grm='git reset --mixed'
alias grb='git rebase'
alias gst='git stash'
alias gstp='git stash pop'
