---
- name: ln -s .gitconfig
  file:
    src: "{{ lookup('fileglob', '.gitconfig') }}"
    dest: ~/.gitconfig
    mode: 0640
    state: link

- name: Create a directory if it does not exist
  file:
    path: ~/.config/git
    state: directory
    recurse: true

- name: ln -s .gitconfig
  file:
    src: "{{ lookup('fileglob', 'ignore') }}"
    dest: ~/.config/git/ignore
    mode: 0640
    state: link

- name: create ssh config if not exist
  file:
    path: ~/.ssh/config
    mode: 0600
    state: touch

- name: ssh config
  lineinfile:
    path: ~/.ssh/config
    state: present
    line: |
      Host github.com
          HostName github.com
          IdentityFile ~/.ssh/github
          User git
  when: lookup("file", "~/.ssh/config") | regex_search("Host github.com") == none
